api_id = "18579024"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         #)<@scaMmEr<
api_hash = "124981da628d86e21ee492da77cd4037"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               #)sCaMMER^
bot_token = "7351725100:AAGr8LG84zenk2OUoOrobUsC-GSyu9QDwaw"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              #-=(ScAMMeR>
FORCE_CHANNEL = 'testsujal'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           #@_&ScAMmeR#<+
LOGS_CHANNEL = -1002212446748                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            #^ScAmmeR%%*
OWNER = 7168441486                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       #$^sCAmMer_
image = 'logo.jpg'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      #(SCammER-
MONGO_URI = 'mongodb+srv://vikassonawale0:JWyQFas7vlG1bkaL@cluster0.beermge.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             #<##sCAMmer$)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           #<##sCAMmer$)
name = 'saksham'
OWNER_USERNAME = 'Annukoushal'

START_TEXT="""
I'm Batch-Txt Extractor bot....!

🚀 Made By @Kingextractor🚀

Usage : First select the app listed below. ⤵️
"""
START_TEXT1="""
I'm Batch-Txt Extractor bot....!

🎯 Made By @sakshambhaiya 🎯
🔰  Now, select the course listed below. 📌
"""
START_TEXTCP="""
I'm CLASSPLUS Extractor bot....!

⤵️  Now, select the Option listed below. 🎯
"""
START_TEXTAPPX="""
I'm APPX Extractor bot....!

🔰  Now, select the Option listed below. 🎯
"""
START_TEXTCP1="""
I'm Going to Generate Auth Token....!

🎯  Now, select the Methods to Geneterate Classplus Auth Token. ✅
"""
HELP_TEXT="""
I'm Batch extractor bot...!
🚀Commands

/helper - For Extracting Txts.

⚠️ Save this id » @sakshambhaiya in case of Copyright infringement.
"""

